# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
# gem "github-pages", "~> GITHUB-PAGES-VERSION", group: :jekyll_plugins
#gem "github-pages", group: :jekyll_plugins
gem "jekyll"
gem "jekyll-remote-theme"
#gem "just-the-docs"